config/routes.rb
Rails.application.routes.draw do
  resources :locations
  root 'locations#index'
  get 'new'  => 'locations#new'

  

end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address  # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  
def temp
  json = ForecastIO.forecast(latitude, longitude)
  json.currently.temperature
end

end

app/models/weather.rb
class Weather
  attr_accessor :location

  def initialize(location)
    @location = location

  end

  def currently
    ForecastIO.forecast(location.latitude, location.longitude, location.temperature).try(:currently).try(:icon)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  
  # GET /locations/1
  # GET /locations/1.json
  def show

  end

  # GET /locations/new
  def new
    @location = Location.new
    
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Votre plage est enregistrée' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Votre Plage est mise à jour.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Plage Supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackathonSea</title>
      <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.haml
%p#notice= notice
%script{:src => "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", :type => "text/javascript"}

%script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}

%h1 Listes de vos plages préfèrées
%table
  %thead
    %tr
      %th Adresse
      %th Latitude
      %th Longitude
      %th{:colspan => "3"}
  %tbody
    - @locations.each do |location|
      %tr
        %td= location.address
        %td= location.latitude
        %td= location.longitude
        %td= link_to 'Voir', location
        %td= link_to 'Modifier', edit_location_path(location)
        %td= link_to 'Supprimer', location, method: :delete, data: { confirm: 'Etes Vous sur ?' }

= link_to 'Rechercher une nouvelle Plage', new_location_path
%br/
- @locations.each do |loc|
  %p= loc.temp

%div{:style => "width: 800px;"}
  #map{:style => "width: 800px; height: 400px;"}
:javascript
  handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(#{raw @hash.to_json});
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
	

app/views/locations/new.html.erb
<h1>Vous souhiatez enregistrer une nouvelle Plage</h1>

<%= render 'form' %>

 
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

 <%= link_to 'Retour', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adresse:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>